os:
  - linux
language: go

addons:
    artifacts:
        debug: true
        paths:
        - $GOPATH/bin

dist: trusty

go:
    - "1.10"

script:
    - set -e
    # Run tests
    - go test github.com/honeycombio/samproxy/...
    # Build binary and packages
    - go install -ldflags "-X main.BuildID=1.${TRAVIS_BUILD_NUMBER}" github.com/honeycombio/samproxy/...
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-pkg.sh -v "1.${TRAVIS_BUILD_NUMBER}" -t deb; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build-pkg.sh -v "1.${TRAVIS_BUILD_NUMBER}" -t rpm; fi
    # Check that packages install
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pkg-test/test.sh "1.${TRAVIS_BUILD_NUMBER}"; fi

before_install:
    # Install fpm for deb/rpm package building
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y build-essential rpm; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install fpm; fi

install:
        - true # HACK: fixes travis-CI lack of support for vendor/ + godeps
