name: Apply project labels
on: [issues, pull_request_target, label]
jobs:
  apply-labels:
    runs-on: ubuntu-latest
    name: Apply common project labels
    permissions:
      pull-requests: write

    steps:
      - uses: honeycombio/oss-management-actions/labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
